baseURL = "https://ebcrowder.dev/"
languageCode = "en-us"
title = "Eric Crowder"

[permalinks]
  blog = "/:filename/"

[params]
  homeText = "You just made a Hugo blog from scratch."

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4