baseURL = "https://ebcrowder.dev/"
languageCode = "en-us"
title = "Eric Crowder"

[permalinks]
  blog = "/:filename/"

[params]

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    noClasses = true
    style = "friendly"
    tabWidth = 4